version: '3.4'

services:
  SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123# 
  logiceacardsmanagementapp2:
    image: ${DOCKER_REGISTRY-}logiceacardsmanagementapp2
    ports:
    - 8001:80 
    build:
      context: .
      dockerfile: LogiceaCardsManagementApp/Dockerfile
    depends_on:
            - SqlServerDb
 
